spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test?characterEncoding=utf8&useSSL=false
    username: test
    password: test

mybatis:
  type-aliases-package: com.example.mapper
  config-location: mybatis/mybatis-config.xml

logging:
  level: trace

