spring:
  datasource:
    url: jdbc:mysql://52.80.49.240/db_location?characterEncoding=utf8&useSSL=false
    username: family_doctor
    password: d$QNvwJ#dN76&%60
  jpa:
    show-sql: true

mybatis:
  type-aliases-package: com.example.mapper
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml

logging:
  level.*: debug

