package com.example.demo.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.List;

public class Regionalism {

    private List<Regionalism> subList;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.id
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    @JsonIgnore
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.region_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    private Long regionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.region_name
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.parent_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    @JsonIgnore
    private Integer parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.remarks
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    @JsonIgnore
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column regionalism.del_flag
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    @JsonIgnore
    private String delFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.id
     *
     * @return the value of regionalism.id
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.id
     *
     * @param id the value for regionalism.id
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.region_code
     *
     * @return the value of regionalism.region_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public Long getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.region_code
     *
     * @param regionCode the value for regionalism.region_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setRegionCode(Long regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.region_name
     *
     * @return the value of regionalism.region_name
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.region_name
     *
     * @param regionName the value for regionalism.region_name
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.parent_code
     *
     * @return the value of regionalism.parent_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public Integer getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.parent_code
     *
     * @param parentCode the value for regionalism.parent_code
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setParentCode(Integer parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.remarks
     *
     * @return the value of regionalism.remarks
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.remarks
     *
     * @param remarks the value for regionalism.remarks
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column regionalism.del_flag
     *
     * @return the value of regionalism.del_flag
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column regionalism.del_flag
     *
     * @param delFlag the value for regionalism.del_flag
     *
     * @mbg.generated Mon Sep 25 11:06:52 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }

    public List<Regionalism> getSubList() {
        return subList;
    }

    public void setSubList(List<Regionalism> subList) {
        this.subList = subList;
    }

    @Override
    public String toString() {
        return "Regionalism{" +
                "id=" + id +
                ", regionCode=" + regionCode +
                ", regionName='" + regionName + '\'' +
                ", parentCode=" + parentCode +
                ", remarks='" + remarks + '\'' +
                ", delFlag='" + delFlag + '\'' +
                '}';
    }
}