package com.example.demo.mapper;

import com.example.demo.entity.LastLevelRegion;
import com.example.demo.entity.Region;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Tue Sep 26 11:25:03 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Tue Sep 26 11:25:03 CST 2017
     */
    int insert(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Tue Sep 26 11:25:03 CST 2017
     */
    Region selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Tue Sep 26 11:25:03 CST 2017
     */
    List<Region> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table region
     *
     * @mbg.generated Tue Sep 26 11:25:03 CST 2017
     */
    int updateByPrimaryKey(Region record);

    List<Region> findRegion(Region region);

    List<LastLevelRegion> findLastLevelRegion(Region region);

}